name: Installing Python

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}      # Use matrix OS value
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        py-version: [3.10, 3.11, 3.12]   # Python versions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}

      - name: Show Python version
        run: python --version
