name: Installing Python

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        py-version: [3.14.0, 3.14.0, 3.14.0]
        exclude:
          - os: macos-14
            py-version: 3.12   # Excluded combination
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}

      - name: Show Python version
        run: python --version
